version: '3.8'
services:
  app:
    build: .
    container_name: comeia_container
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    environment:
      - VITE_WEATHER_API_KEY="53ef7a31ac5142c193b221122220812"
