export const weatherMock = {
  location: {
    name: 'Caruaru',
    region: 'Pernambuco',
    country: 'Brazil',
    lat: -8.28,
    lon: -35.97,
    tz_id: 'America/Recife',
    localtime_epoch: 1670766376,
    localtime: '2022-12-11 10:46'
  },
  current: {
    last_updated_epoch: 1670766300,
    last_updated: '2022-12-11 10:45',
    temp_c: 29.6,
    temp_f: 85.3,
    is_day: 1,
    condition: {
      text: 'Partly cloudy',
      icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
      code: 1003
    },
    wind_mph: 11,
    wind_kph: 17.6,
    wind_degree: 109,
    wind_dir: 'ESE',
    pressure_mb: 1014,
    pressure_in: 29.93,
    precip_mm: 0,
    precip_in: 0,
    humidity: 46,
    cloud: 36,
    feelslike_c: 30.3,
    feelslike_f: 86.5,
    vis_km: 10,
    vis_miles: 6,
    uv: 7,
    gust_mph: 12.5,
    gust_kph: 20.2
  },
  forecast: {
    forecastday: [
      {
        date: '2022-12-11',
        date_epoch: 1670716800,
        day: {
          maxtemp_c: 34.9,
          maxtemp_f: 94.8,
          mintemp_c: 19.9,
          mintemp_f: 67.8,
          avgtemp_c: 25.1,
          avgtemp_f: 77.2,
          maxwind_mph: 17.2,
          maxwind_kph: 27.7,
          totalprecip_mm: 0.1,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 9.7,
          avgvis_miles: 6,
          avghumidity: 70,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003
          },
          uv: 7
        },
        astro: {
          sunrise: '04:59 AM',
          sunset: '05:35 PM',
          moonrise: '08:38 PM',
          moonset: '07:40 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: '77'
        },
        hour: [
          {
            time_epoch: 1670727600,
            time: '2022-12-11 00:00',
            temp_c: 21.2,
            temp_f: 70.2,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 107,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 75,
            feelslike_c: 21.2,
            feelslike_f: 70.2,
            windchill_c: 21.2,
            windchill_f: 70.2,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 19.9,
            dewpoint_f: 67.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 1
          },
          {
            time_epoch: 1670731200,
            time: '2022-12-11 01:00',
            temp_c: 21,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 113,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 75,
            feelslike_c: 21,
            feelslike_f: 69.8,
            windchill_c: 21,
            windchill_f: 69.8,
            heatindex_c: 21,
            heatindex_f: 69.8,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1
          },
          {
            time_epoch: 1670734800,
            time: '2022-12-11 02:00',
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 109,
            wind_dir: 'ESE',
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 80,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 18.9,
            dewpoint_f: 66,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1
          },
          {
            time_epoch: 1670738400,
            time: '2022-12-11 03:00',
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 106,
            wind_dir: 'ESE',
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 91,
            cloud: 71,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 19,
            dewpoint_f: 66.2,
            will_it_rain: 0,
            chance_of_rain: 61,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1
          },
          {
            time_epoch: 1670742000,
            time: '2022-12-11 04:00',
            temp_c: 20.1,
            temp_f: 68.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 106,
            wind_dir: 'ESE',
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 91,
            cloud: 61,
            feelslike_c: 20.1,
            feelslike_f: 68.2,
            windchill_c: 20.1,
            windchill_f: 68.2,
            heatindex_c: 20.1,
            heatindex_f: 68.2,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1
          },
          {
            time_epoch: 1670745600,
            time: '2022-12-11 05:00',
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 112,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 64,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 4
          },
          {
            time_epoch: 1670749200,
            time: '2022-12-11 06:00',
            temp_c: 21.1,
            temp_f: 70,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 113,
            wind_dir: 'ESE',
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 67,
            feelslike_c: 21.1,
            feelslike_f: 70,
            windchill_c: 21.1,
            windchill_f: 70,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 19,
            dewpoint_f: 66.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 5
          },
          {
            time_epoch: 1670752800,
            time: '2022-12-11 07:00',
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 107,
            wind_dir: 'ESE',
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 66,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 5
          },
          {
            time_epoch: 1670756400,
            time: '2022-12-11 08:00',
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 106,
            wind_dir: 'ESE',
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 78,
            feelslike_c: 26.8,
            feelslike_f: 80.2,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 26.8,
            heatindex_f: 80.2,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 6
          },
          {
            time_epoch: 1670760000,
            time: '2022-12-11 09:00',
            temp_c: 27.4,
            temp_f: 81.3,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 106,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 33,
            feelslike_c: 28.5,
            feelslike_f: 83.3,
            windchill_c: 27.4,
            windchill_f: 81.3,
            heatindex_c: 28.5,
            heatindex_f: 83.3,
            dewpoint_c: 17.7,
            dewpoint_f: 63.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 7
          },
          {
            time_epoch: 1670763600,
            time: '2022-12-11 10:00',
            temp_c: 29.6,
            temp_f: 85.3,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 109,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 46,
            cloud: 36,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 29.6,
            windchill_f: 85.3,
            heatindex_c: 30.3,
            heatindex_f: 86.5,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 7
          },
          {
            time_epoch: 1670767200,
            time: '2022-12-11 11:00',
            temp_c: 32,
            temp_f: 89.6,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 111,
            wind_dir: 'ESE',
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 39,
            cloud: 19,
            feelslike_c: 32.8,
            feelslike_f: 91,
            windchill_c: 32,
            windchill_f: 89.6,
            heatindex_c: 32.8,
            heatindex_f: 91,
            dewpoint_c: 16.4,
            dewpoint_f: 61.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.9,
            gust_kph: 22.3,
            uv: 8
          },
          {
            time_epoch: 1670770800,
            time: '2022-12-11 12:00',
            temp_c: 34.9,
            temp_f: 94.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 114,
            wind_dir: 'ESE',
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            humidity: 36,
            cloud: 12,
            feelslike_c: 36.6,
            feelslike_f: 97.9,
            windchill_c: 34.9,
            windchill_f: 94.8,
            heatindex_c: 36.6,
            heatindex_f: 97.9,
            dewpoint_c: 17.4,
            dewpoint_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.3,
            gust_kph: 23,
            uv: 8
          },
          {
            time_epoch: 1670774400,
            time: '2022-12-11 13:00',
            temp_c: 32.7,
            temp_f: 90.9,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 120,
            wind_dir: 'ESE',
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 35,
            cloud: 30,
            feelslike_c: 33.1,
            feelslike_f: 91.6,
            windchill_c: 32.7,
            windchill_f: 90.9,
            heatindex_c: 33.1,
            heatindex_f: 91.6,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 8
          },
          {
            time_epoch: 1670778000,
            time: '2022-12-11 14:00',
            temp_c: 32.1,
            temp_f: 89.8,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003
            },
            wind_mph: 15.7,
            wind_kph: 25.2,
            wind_degree: 126,
            wind_dir: 'SE',
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            humidity: 38,
            cloud: 35,
            feelslike_c: 32.6,
            feelslike_f: 90.7,
            windchill_c: 32.1,
            windchill_f: 89.8,
            heatindex_c: 32.6,
            heatindex_f: 90.7,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.1,
            gust_kph: 29.2,
            uv: 8
          },
          {
            time_epoch: 1670781600,
            time: '2022-12-11 15:00',
            temp_c: 30.2,
            temp_f: 86.4,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000
            },
            wind_mph: 17.2,
            wind_kph: 27.7,
            wind_degree: 132,
            wind_dir: 'SE',
            pressure_mb: 1010,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            humidity: 46,
            cloud: 20,
            feelslike_c: 31.2,
            feelslike_f: 88.2,
            windchill_c: 30.2,
            windchill_f: 86.4,
            heatindex_c: 31.2,
            heatindex_f: 88.2,
            dewpoint_c: 17.3,
            dewpoint_f: 63.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.9,
            gust_kph: 32,
            uv: 8
          },
          {
            time_epoch: 1670785200,
            time: '2022-12-11 16:00',
            temp_c: 28.4,
            temp_f: 83.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000
            },
            wind_mph: 15,
            wind_kph: 24.1,
            wind_degree: 126,
            wind_dir: 'SE',
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 23,
            feelslike_c: 29.6,
            feelslike_f: 85.3,
            windchill_c: 28.4,
            windchill_f: 83.1,
            heatindex_c: 29.6,
            heatindex_f: 85.3,
            dewpoint_c: 18.1,
            dewpoint_f: 64.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.2,
            gust_kph: 27.7,
            uv: 7
          },
          {
            time_epoch: 1670788800,
            time: '2022-12-11 17:00',
            temp_c: 27,
            temp_f: 80.6,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 114,
            wind_dir: 'ESE',
            pressure_mb: 1011,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 21,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 27,
            windchill_f: 80.6,
            heatindex_c: 28.3,
            heatindex_f: 82.9,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 7
          },
          {
            time_epoch: 1670792400,
            time: '2022-12-11 18:00',
            temp_c: 26,
            temp_f: 78.8,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 103,
            wind_dir: 'ESE',
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 8,
            feelslike_c: 27.7,
            feelslike_f: 81.9,
            windchill_c: 26,
            windchill_f: 78.8,
            heatindex_c: 27.7,
            heatindex_f: 81.9,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 1
          },
          {
            time_epoch: 1670796000,
            time: '2022-12-11 19:00',
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 96,
            wind_dir: 'E',
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 16,
            feelslike_c: 26.1,
            feelslike_f: 79,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 26.1,
            heatindex_f: 79,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 1
          },
          {
            time_epoch: 1670799600,
            time: '2022-12-11 20:00',
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 93,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 19,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 1
          },
          {
            time_epoch: 1670803200,
            time: '2022-12-11 21:00',
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 93,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 37,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1
          },
          {
            time_epoch: 1670806800,
            time: '2022-12-11 22:00',
            temp_c: 21.1,
            temp_f: 70,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 93,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 65,
            feelslike_c: 21.1,
            feelslike_f: 70,
            windchill_c: 21.1,
            windchill_f: 70,
            heatindex_c: 24.1,
            heatindex_f: 75.4,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 1
          },
          {
            time_epoch: 1670810400,
            time: '2022-12-11 23:00',
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 91,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 79,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 19.9,
            dewpoint_f: 67.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1
          }
        ]
      }
    ]
  }
}
